name: Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      apply:
        description: 'Executar terraform apply?'
        required: true
        default: 'false'
        type: choice
        options:
          - true
          - false
      destroy:
        description: 'Destruir ambiente?'
        required: true
        default: 'false'
        type: choice
        options:
          - true
          - false
      plan_destroy:
        description: 'Planejar o destroy?'
        required: true
        default: 'false'
        type: choice
        options:
          - true
          - false

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::523083723304:role/github-actions-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event.inputs.apply == 'true'
        run: terraform apply -auto-approve tfplan

      - name: Plan Destroy
        if: github.event.inputs.plan_destroy == 'true'
        run: terraform plan -destroy -out=tfplandestroy

      - name: Terraform Destroy
        if: github.event.inputs.destroy == 'true'
        run: terraform apply -destroy -auto-approve tfplandestroy
